version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guvi-reactjs-container
    image: reactjs-guvi:latest
    ports:
      - "3000:80"
   
